// PROJECT ACTIONS
export const GET_USER = "GET_USER";
export const USERS_ERROR = "USERS_ERROR";

export const FETCH_WORK_PACKAGE_REQUEST = "FETCH_WORK_PACKAGE_REQUEST";
export const FETCH_WORK_PACKAGE_SUCCESS = "FETCH_WORK_PACKAGE_SUCCESS";
export const FETCH_WORK_PACKAGE_FAILURE = "FETCH_WORK_PACKAGE_FAILURE";
export const REORDER_WORK_PACKAGE_ROWS = "REORDER_WORK_PACKAGE_ROWS";
export const UPDATE_WORK_PACKAGE_ROW = "UPDATE_WORK_PACKAGE_ROW";
export const REMOVE_WORK_PACKAGE_ROW = "REMOVE_WORK_PACKAGE_ROW";
export const ROW_ADDED = "ROW_ADDED";
