// PROJECT ACTIONS
export const GET_USER = "GET_USER";
export const USERS_ERROR = "USERS_ERROR";


export const FETCH_GANTT_REQUEST = "FETCH_GANTT_REQUEST";
export const FETCH_GANTT_SUCCESS = "FETCH_GANTT_SUCCESS";
export const FETCH_GANTT_FAILURE = "FETCH_GANTT_FAILURE";
export const MOVE_GANTT_ROWS = "MOVE_GANTT_ROWS";
export const REASSIGN_GANTT_BLOCKS = "REASSIGN_GANTT_BLOCKS";
